version: "3.9"
services:
    backendv3:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "9001"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "3ggwarD_"
            ACCEPT_EULA: "Y"